import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, setDoc, doc, deleteDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyAIceqMXYNY5EH_3vTmIbogjb6wJ2CCBxQ",
  authDomain: "speakup-27de0.firebaseapp.com",
  databaseURL: "https://speakup-27de0-default-rtdb.firebaseio.com",
  projectId: "speakup-27de0",
  storageBucket: "speakup-27de0.firebasestorage.app",
  messagingSenderId: "811108429557",
  appId: "1:811108429557:web:1ad8de2151de43b8f8dfbc",
  measurementId: "G-BQ65T23S3M",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const SEED_PRODUCTS = [
  {
    slug: "tech-pique-t-shirt",
    name: "Tech Pique T-Shirt",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Men",
    description: "A lightweight, breathable t-shirt crafted from performance piqué fabric. Features a classic crew neck and the iconic AV APPAREL logo on the chest.",
    details: "Crew neck. Short sleeves. AV logo patch on chest. Ribbed collar. Regular fit. Machine washable.",
    materials: "60% Cotton, 40% Polyester. Machine wash cold. Tumble dry low.",
    price: 59.0,
    salePrice: 35.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
      "https://images.unsplash.com/photo-1622445275576-721325763afe?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Bright White", colorHex: "#FFFFFF", stock: 15 },
      { size: "S", color: "Bright White", colorHex: "#FFFFFF", stock: 22 },
      { size: "M", color: "Bright White", colorHex: "#FFFFFF", stock: 30 },
      { size: "L", color: "Bright White", colorHex: "#FFFFFF", stock: 18 },
      { size: "XL", color: "Bright White", colorHex: "#FFFFFF", stock: 10 },
      { size: "XXL", color: "Bright White", colorHex: "#FFFFFF", stock: 5 },
      { size: "S", color: "Black Beauty", colorHex: "#111111", stock: 20 },
      { size: "M", color: "Black Beauty", colorHex: "#111111", stock: 25 },
      { size: "L", color: "Black Beauty", colorHex: "#111111", stock: 15 },
      { size: "XL", color: "Black Beauty", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 12 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "S", color: "AV Navy", colorHex: "#1B2A4A", stock: 14 },
      { size: "M", color: "AV Navy", colorHex: "#1B2A4A", stock: 20 },
      { size: "L", color: "AV Navy", colorHex: "#1B2A4A", stock: 11 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["basics", "performance", "spring"],
    rating: 4.2,
    reviewCount: 5,
    createdAt: "2026-01-15",
  },
  {
    slug: "slim-tapered-jeans",
    name: "Slim Tapered Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "A modern slim tapered fit in premium stretch denim. Sits below the waist with a slim fit through the hip and thigh that tapers to the ankle.",
    details: "5-pocket styling. Zip fly with button closure. AV APPAREL leather patch at back waist. Slim tapered fit.",
    materials: "98% Cotton, 2% Elastane. Machine wash cold inside out. Tumble dry low.",
    price: 119.0,
    salePrice: 71.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80"
    ],
    variants: [
      { size: "28", color: "Raw Rinse", colorHex: "#1a2744", stock: 10 },
      { size: "30", color: "Raw Rinse", colorHex: "#1a2744", stock: 15 },
      { size: "32", color: "Raw Rinse", colorHex: "#1a2744", stock: 20 },
      { size: "34", color: "Raw Rinse", colorHex: "#1a2744", stock: 12 },
      { size: "36", color: "Raw Rinse", colorHex: "#1a2744", stock: 8 },
      { size: "30", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 14 },
      { size: "32", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 18 },
      { size: "34", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 10 },
      { size: "30", color: "Light Wash", colorHex: "#a5c4e0", stock: 11 },
      { size: "32", color: "Light Wash", colorHex: "#a5c4e0", stock: 16 },
      { size: "34", color: "Light Wash", colorHex: "#a5c4e0", stock: 9 },
      { size: "30", color: "Black", colorHex: "#111111", stock: 13 },
      { size: "32", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "34", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["denim", "spring", "essentials"],
    rating: 4.5,
    reviewCount: 6,
    createdAt: "2025-11-20",
  },
  {
    slug: "trouser-barrel-jeans",
    name: "Trouser Barrel Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "Wide-leg barrel fit in premium twill. A relaxed, vintage-inspired silhouette with pleated front and cropped length.",
    details: "Pleated front. Zip fly with button closure. Barrel leg silhouette. Cropped length. AV patch at back waist.",
    materials: "100% Cotton. Machine wash cold. Hang dry recommended.",
    price: 149.0,
    salePrice: 89.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80",
      "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&q=80"
    ],
    variants: [
      { size: "30", color: "Khaki", colorHex: "#C3B091", stock: 8 },
      { size: "32", color: "Khaki", colorHex: "#C3B091", stock: 12 },
      { size: "34", color: "Khaki", colorHex: "#C3B091", stock: 10 },
      { size: "30", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "32", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "34", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["denim", "spring", "90s"],
    rating: 4.0,
    reviewCount: 1,
    createdAt: "2026-02-01",
  },
  {
    slug: "varsity-logo-fleece-sweatshirt",
    name: "Varsity Logo Graphic Fleece Sweatshirt",
    category: "Tops",
    subcategory: "Sweatshirts",
    gender: "Men",
    description: "A cozy fleece sweatshirt with oversized varsity-style AV APPAREL logo across the chest.",
    details: "Crew neck. Ribbed cuffs and hem. Large varsity AV logo graphic on chest. Relaxed fit.",
    materials: "80% Cotton, 20% Polyester. Machine wash cold. Tumble dry low.",
    price: 89.0,
    salePrice: 53.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80",
      "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 14 },
      { size: "XL", color: "Grey Heather", colorHex: "#9B9B9B", stock: 8 },
      { size: "S", color: "Black Beauty", colorHex: "#111111", stock: 12 },
      { size: "M", color: "Black Beauty", colorHex: "#111111", stock: 20 },
      { size: "L", color: "Black Beauty", colorHex: "#111111", stock: 15 },
      { size: "XL", color: "Black Beauty", colorHex: "#111111", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["casual", "logo", "cozy"],
    rating: 4.3,
    reviewCount: 0,
    createdAt: "2025-12-05",
  },
  {
    slug: "lightweight-windbreaker-jacket",
    name: "Lightweight Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A water-resistant windbreaker with packable design. Features a half-zip front, elastic cuffs, and the AV logo.",
    details: "Half-zip front. Packable into pocket. Elastic cuffs. Drawcord at hem. AV logo embroidery.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 149.0,
    salePrice: 59.6,
    discount: 60,
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
      "https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Chase Blue", colorHex: "#4A90D9", stock: 3 },
      { size: "S", color: "Chase Blue", colorHex: "#4A90D9", stock: 7 },
      { size: "M", color: "Chase Blue", colorHex: "#4A90D9", stock: 12 },
      { size: "L", color: "Chase Blue", colorHex: "#4A90D9", stock: 8 },
      { size: "XL", color: "Chase Blue", colorHex: "#4A90D9", stock: 4 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 15 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 11 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 5 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear", "active"],
    rating: 4.6,
    reviewCount: 3,
    createdAt: "2025-10-10",
  },
  {
    slug: "ombre-windbreaker-jacket",
    name: "Ombre Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A standout ombre-dyed windbreaker with gradient colorway. Lightweight water-resistant nylon.",
    details: "Full zip front. Ombre dye effect. Stand collar. Two side pockets. Elastic cuffs and hem.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 199.0,
    salePrice: 79.6,
    discount: 60,
    images: [
      "https://images.unsplash.com/photo-1544923246-77307dd270b3?w=600&q=80",
      "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Orange Gradient", colorHex: "#FF6B35", stock: 6 },
      { size: "M", color: "Orange Gradient", colorHex: "#FF6B35", stock: 10 },
      { size: "L", color: "Orange Gradient", colorHex: "#FF6B35", stock: 8 },
      { size: "XL", color: "Orange Gradient", colorHex: "#FF6B35", stock: 4 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear"],
    rating: 4.1,
    reviewCount: 2,
    createdAt: "2025-09-20",
  },
  {
    slug: "nylon-bomber-jacket",
    name: "Nylon Bomber Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A classic bomber jacket updated in lightweight nylon. Ribbed collar, cuffs and hem.",
    details: "Two-way zip front. Ribbed collar, cuffs, and hem. Two side pockets. Interior pocket.",
    materials: "Shell: 100% Nylon. Lining: 100% Polyester. Machine wash cold.",
    price: 149.0,
    salePrice: 59.6,
    discount: 60,
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
      "https://images.unsplash.com/photo-1557183305-a0310a4fae30?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 9 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 5 },
      { size: "M", color: "Olive", colorHex: "#556B2F", stock: 8 },
      { size: "L", color: "Olive", colorHex: "#556B2F", stock: 11 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear", "bomber"],
    rating: 4.4,
    reviewCount: 4,
    createdAt: "2025-10-15",
  },
  {
    slug: "90s-straight-jeans",
    name: "90s Straight Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "Authentic 90s-inspired straight leg fit. Sits at the waist with a straight fit through hip, thigh, and leg.",
    details: "5-pocket styling. Zip fly with button closure. 90s straight leg. CK leather patch.",
    materials: "99% Cotton, 1% Elastane. Machine wash cold inside out.",
    price: 169.0,
    salePrice: 84.5,
    discount: 50,
    images: [
      "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=600&q=80",
      "https://images.unsplash.com/photo-1475178626620-a4d074967452?w=600&q=80"
    ],
    variants: [
      { size: "28", color: "Mid Blue", colorHex: "#4682B4", stock: 8 },
      { size: "30", color: "Mid Blue", colorHex: "#4682B4", stock: 14 },
      { size: "32", color: "Mid Blue", colorHex: "#4682B4", stock: 20 },
      { size: "34", color: "Mid Blue", colorHex: "#4682B4", stock: 12 },
      { size: "36", color: "Mid Blue", colorHex: "#4682B4", stock: 6 },
      { size: "30", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 10 },
      { size: "32", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 15 },
      { size: "34", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 8 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["denim", "90s", "essentials"],
    rating: 4.7,
    reviewCount: 12,
    createdAt: "2025-08-05",
  },
  {
    slug: "modern-cotton-boxer-brief-3-pack",
    name: "Modern Cotton Boxer Brief 3-Pack",
    category: "Underwear",
    subcategory: "Boxer Briefs",
    gender: "Men",
    description: "The iconic AV APPAREL waistband on a cotton stretch boxer brief. Sold in a pack of three.",
    details: "Signature AV waistband. Cotton stretch fabric. Contour pouch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 49.5,
    salePrice: null,
    discount: 0,
    images: [
      "https://images.unsplash.com/photo-1617331140180-e8262094733a?w=600&q=80",
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Black/White/Grey", colorHex: "#111111", stock: 25 },
      { size: "M", color: "Black/White/Grey", colorHex: "#111111", stock: 35 },
      { size: "L", color: "Black/White/Grey", colorHex: "#111111", stock: 30 },
      { size: "XL", color: "Black/White/Grey", colorHex: "#111111", stock: 18 },
      { size: "S", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 15 },
      { size: "M", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 22 },
      { size: "L", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 18 },
      { size: "XL", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["underwear", "basics", "essentials"],
    rating: 4.8,
    reviewCount: 45,
    createdAt: "2025-06-01",
  },
  {
    slug: "cotton-stretch-trunk-3-pack",
    name: "Cotton Stretch Trunk 3-Pack",
    category: "Underwear",
    subcategory: "Trunks",
    gender: "Men",
    description: "Classic AV APPAREL trunks in soft cotton stretch. Signature waistband and low-rise fit.",
    details: "Signature AV waistband. Low-rise fit. Cotton stretch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 49.5,
    salePrice: 34.65,
    discount: 30,
    images: [
      "https://images.unsplash.com/photo-1617331140180-e8262094733a?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 30 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 25 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 12 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["underwear", "basics"],
    rating: 4.6,
    reviewCount: 22,
    createdAt: "2025-06-15",
  },
  {
    slug: "relaxed-fit-archive-logo-tee",
    name: "Relaxed Fit Archive Logo Tee",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Women",
    description: "An oversized relaxed fit T-shirt featuring the classic AV APPAREL archive logo.",
    details: "Crew neck. Dropped shoulder. AV archive logo print. Relaxed oversized fit.",
    materials: "100% Cotton. Machine wash cold.",
    price: 49.0,
    salePrice: 29.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80",
      "https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "S", color: "White", colorHex: "#FFFFFF", stock: 20 },
      { size: "M", color: "White", colorHex: "#FFFFFF", stock: 25 },
      { size: "L", color: "White", colorHex: "#FFFFFF", stock: 15 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 22 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["basics", "logo", "casual"],
    rating: 4.4,
    reviewCount: 18,
    createdAt: "2025-09-01",
  },
  {
    slug: "high-rise-straight-jeans",
    name: "High Rise Straight Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Women",
    description: "A flattering high-rise straight leg jean with vintage-inspired washes.",
    details: "High rise. Straight leg. 5-pocket styling. Zip fly with button closure.",
    materials: "99% Cotton, 1% Elastane. Machine wash cold.",
    price: 129.0,
    salePrice: 77.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
      "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=600&q=80"
    ],
    variants: [
      { size: "24", color: "Light Indigo", colorHex: "#8DAFCE", stock: 8 },
      { size: "25", color: "Light Indigo", colorHex: "#8DAFCE", stock: 12 },
      { size: "26", color: "Light Indigo", colorHex: "#8DAFCE", stock: 16 },
      { size: "27", color: "Light Indigo", colorHex: "#8DAFCE", stock: 14 },
      { size: "28", color: "Light Indigo", colorHex: "#8DAFCE", stock: 10 },
      { size: "29", color: "Light Indigo", colorHex: "#8DAFCE", stock: 8 },
      { size: "30", color: "Light Indigo", colorHex: "#8DAFCE", stock: 6 },
      { size: "25", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "26", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "27", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "28", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["denim", "essentials", "90s"],
    rating: 4.3,
    reviewCount: 9,
    createdAt: "2026-01-10",
  },
  {
    slug: "modern-cotton-bralette",
    name: "Modern Cotton Bralette",
    category: "Underwear",
    subcategory: "Bralettes",
    gender: "Women",
    description: "The iconic AV APPAREL bralette in soft modern cotton with signature logo waistband.",
    details: "Signature AV waistband. Unlined. Pullover style. Scoop neck. Racerback.",
    materials: "53% Cotton, 35% Modal, 12% Elastane. Machine wash cold.",
    price: 34.0,
    salePrice: null,
    discount: 0,
    images: [
      "https://images.unsplash.com/photo-1582142306909-195724d33ffc?w=600&q=80",
      "https://images.unsplash.com/photo-1571166574885-aef7e738b00b?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 30 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 28 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 15 },
      { size: "XS", color: "Grey Heather", colorHex: "#9B9B9B", stock: 14 },
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 22 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "XS", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 12 },
      { size: "S", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 18 },
      { size: "M", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 16 },
      { size: "L", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 8 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["underwear", "iconic", "basics"],
    rating: 4.7,
    reviewCount: 65,
    createdAt: "2025-04-01",
  },
  {
    slug: "cropped-denim-jacket",
    name: "Cropped Denim Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Women",
    description: "A cropped denim jacket with a classic fit and AV branding.",
    details: "Button-front closure. Two chest pockets. Side pockets. Cropped length.",
    materials: "100% Cotton. Machine wash cold.",
    price: 139.0,
    salePrice: 83.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1527016021513-b09758b777bd?w=600&q=80",
      "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Light Wash", colorHex: "#B8D4E8", stock: 6 },
      { size: "S", color: "Light Wash", colorHex: "#B8D4E8", stock: 10 },
      { size: "M", color: "Light Wash", colorHex: "#B8D4E8", stock: 14 },
      { size: "L", color: "Light Wash", colorHex: "#B8D4E8", stock: 8 },
      { size: "S", color: "Mid Blue", colorHex: "#4682B4", stock: 8 },
      { size: "M", color: "Mid Blue", colorHex: "#4682B4", stock: 12 },
      { size: "L", color: "Mid Blue", colorHex: "#4682B4", stock: 6 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["spring", "denim", "outerwear"],
    rating: 4.5,
    reviewCount: 7,
    createdAt: "2026-02-10",
  },
  {
    slug: "cotton-bikini-3-pack",
    name: "Cotton Bikini 3-Pack",
    category: "Underwear",
    subcategory: "Bikinis",
    gender: "Women",
    description: "Everyday cotton bikini with signature AV APPAREL waistband. 3-pack.",
    details: "Signature AV waistband. Bikini cut. Cotton stretch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 39.0,
    salePrice: 27.3,
    discount: 30,
    images: [
      "https://images.unsplash.com/photo-1582142306909-195724d33ffc?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Black/White/Grey", colorHex: "#111111", stock: 18 },
      { size: "S", color: "Black/White/Grey", colorHex: "#111111", stock: 25 },
      { size: "M", color: "Black/White/Grey", colorHex: "#111111", stock: 30 },
      { size: "L", color: "Black/White/Grey", colorHex: "#111111", stock: 16 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["underwear", "basics"],
    rating: 4.5,
    reviewCount: 30,
    createdAt: "2025-07-01",
  },
  {
    slug: "slim-fit-stretch-shirt",
    name: "Slim Fit Stretch Dress Shirt",
    category: "Tops",
    subcategory: "Dress Shirts",
    gender: "Men",
    description: "A refined slim-fit dress shirt crafted from stretch cotton poplin.",
    details: "Spread collar. Button-front. Barrel cuffs. Slim fit through body.",
    materials: "97% Cotton, 3% Elastane. Machine wash cold.",
    price: 79.5,
    salePrice: 47.7,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "M", color: "White", colorHex: "#FFFFFF", stock: 20 },
      { size: "L", color: "White", colorHex: "#FFFFFF", stock: 16 },
      { size: "XL", color: "White", colorHex: "#FFFFFF", stock: 8 },
      { size: "S", color: "Light Blue", colorHex: "#ADD8E6", stock: 10 },
      { size: "M", color: "Light Blue", colorHex: "#ADD8E6", stock: 16 },
      { size: "L", color: "Light Blue", colorHex: "#ADD8E6", stock: 12 },
      { size: "XL", color: "Light Blue", colorHex: "#ADD8E6", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["formal", "essentials", "office"],
    rating: 4.2,
    reviewCount: 11,
    createdAt: "2025-08-15",
  },
  {
    slug: "hooded-softshell-jacket",
    name: "Hooded Softshell Zip Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A versatile hooded softshell jacket. Water-resistant and wind-proof.",
    details: "Full zip front. Attached hood. Softshell stretch fabric. Two zip pockets.",
    materials: "94% Polyester, 6% Elastane. Wipe clean or dry clean.",
    price: 189.0,
    salePrice: 56.7,
    discount: 70,
    images: [
      "https://images.unsplash.com/photo-1544923246-77307dd270b3?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Dark Grey", colorHex: "#444444", stock: 5 },
      { size: "M", color: "Dark Grey", colorHex: "#444444", stock: 10 },
      { size: "L", color: "Dark Grey", colorHex: "#444444", stock: 8 },
      { size: "XL", color: "Dark Grey", colorHex: "#444444", stock: 3 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "active", "performance"],
    rating: 4.5,
    reviewCount: 8,
    createdAt: "2025-09-10",
  },
  {
    slug: "ribbed-knit-midi-dress",
    name: "Ribbed Knit Midi Dress",
    category: "Tops",
    subcategory: "Dresses",
    gender: "Women",
    description: "A bodycon ribbed knit midi dress with minimalist design.",
    details: "Scoop neck. Sleeveless. Bodycon fit. Midi length. AV logo detail.",
    materials: "68% Viscose, 27% Polyester, 5% Elastane. Hand wash cold.",
    price: 99.0,
    salePrice: 59.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "XS", color: "Camel", colorHex: "#C19A6B", stock: 6 },
      { size: "S", color: "Camel", colorHex: "#C19A6B", stock: 10 },
      { size: "M", color: "Camel", colorHex: "#C19A6B", stock: 12 },
      { size: "L", color: "Camel", colorHex: "#C19A6B", stock: 5 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["dresses", "minimalist", "spring"],
    rating: 4.6,
    reviewCount: 4,
    createdAt: "2026-02-20",
  },
  {
    slug: "kids-logo-t-shirt",
    name: "Kids Logo T-Shirt",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Kids",
    description: "A mini version of the iconic AV APPAREL logo tee.",
    details: "Crew neck. Short sleeves. AV logo print on chest. Regular fit.",
    materials: "100% Cotton. Machine wash cold.",
    price: 29.0,
    salePrice: null,
    discount: 0,
    images: [
      "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&q=80"
    ],
    variants: [
      { size: "4", color: "White", colorHex: "#FFFFFF", stock: 12 },
      { size: "5", color: "White", colorHex: "#FFFFFF", stock: 15 },
      { size: "6", color: "White", colorHex: "#FFFFFF", stock: 18 },
      { size: "7", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "8", color: "White", colorHex: "#FFFFFF", stock: 10 },
      { size: "4", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "5", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "6", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "7", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["kids", "basics", "logo"],
    rating: 4.8,
    reviewCount: 20,
    createdAt: "2025-07-15",
  },
  {
    slug: "reversible-puffer-jacket",
    name: "Allover Emblem Logo Reversible Puffer Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A reversible puffer jacket with AV monogram and solid color.",
    details: "Reversible design. Stand collar. Zip front. AV monogram print.",
    materials: "Shell: 100% Polyester. Fill: 80% Down, 20% Feather. Dry clean only.",
    price: 329.0,
    salePrice: 98.7,
    discount: 70,
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&q=80",
      "https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Black/Monogram", colorHex: "#111111", stock: 4 },
      { size: "M", color: "Black/Monogram", colorHex: "#111111", stock: 7 },
      { size: "L", color: "Black/Monogram", colorHex: "#111111", stock: 5 },
      { size: "XL", color: "Black/Monogram", colorHex: "#111111", stock: 2 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "puffer", "sale"],
    rating: 4.3,
    reviewCount: 6,
    createdAt: "2025-08-01",
  },
  {
    slug: "relaxed-hoodie-sweatshirt",
    name: "Relaxed Hoodie Sweatshirt",
    category: "Tops",
    subcategory: "Sweatshirts",
    gender: "Women",
    description: "An oversized relaxed hoodie with kangaroo pocket and drawstring hood.",
    details: "Drawstring hood. Kangaroo pocket. Ribbed cuffs and hem. AV logo embroidery.",
    materials: "80% Cotton, 20% Polyester. Machine wash cold.",
    price: 89.0,
    salePrice: 53.4,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
      "https://images.unsplash.com/photo-1434389677669-e08b4cda3a94?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 10 },
      { size: "S", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 16 },
      { size: "M", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 20 },
      { size: "L", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 12 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["casual", "cozy", "basics"],
    rating: 4.4,
    reviewCount: 14,
    createdAt: "2025-10-20",
  },
  {
    slug: "tech-knit-track-jacket",
    name: "Tech Knit Track Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A sporty track jacket in lightweight tech knit with zip front.",
    details: "Full zip front. Stand collar. Contrast trim at collar and cuffs. Side pockets.",
    materials: "90% Polyester, 10% Elastane. Machine wash cold.",
    price: 189.0,
    salePrice: 56.7,
    discount: 70,
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 4 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["active", "outerwear", "performance"],
    rating: 4.2,
    reviewCount: 5,
    createdAt: "2025-09-25",
  },
  {
    slug: "cotton-modal-sleep-set",
    name: "Cotton Modal Sleep Set",
    category: "Underwear",
    subcategory: "Sleepwear",
    gender: "Women",
    description: "A luxurious sleep set in soft cotton modal.",
    details: "Short sleeve crew neck top. Elastic waist shorts. AV logo.",
    materials: "50% Cotton, 50% Modal. Machine wash cold.",
    price: 68.0,
    salePrice: 40.8,
    discount: 40,
    images: [
      "https://images.unsplash.com/photo-1571166574885-aef7e738b00b?w=600&q=80"
    ],
    variants: [
      { size: "XS", color: "Shoreline", colorHex: "#6EA4BF", stock: 8 },
      { size: "S", color: "Shoreline", colorHex: "#6EA4BF", stock: 14 },
      { size: "M", color: "Shoreline", colorHex: "#6EA4BF", stock: 18 },
      { size: "L", color: "Shoreline", colorHex: "#6EA4BF", stock: 10 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["sleepwear", "essentials"],
    rating: 4.6,
    reviewCount: 16,
    createdAt: "2025-11-01",
  },
  {
    slug: "monogram-windbreaker-jacket",
    name: "Allover Monogram Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A lightweight windbreaker with allover AV monogram print.",
    details: "Full zip front. Hood with drawcord. Allover AV monogram. Two side pockets.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 179.0,
    salePrice: 71.6,
    discount: 60,
    images: [
      "https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&q=80",
      "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=600&q=80"
    ],
    variants: [
      { size: "S", color: "Autumn Green", colorHex: "#556B2F", stock: 5 },
      { size: "M", color: "Autumn Green", colorHex: "#556B2F", stock: 9 },
      { size: "L", color: "Autumn Green", colorHex: "#556B2F", stock: 7 },
      { size: "S", color: "Merlot", colorHex: "#722F37", stock: 4 },
      { size: "M", color: "Merlot", colorHex: "#722F37", stock: 8 },
      { size: "L", color: "Merlot", colorHex: "#722F37", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "monogram", "spring"],
    rating: 4.0,
    reviewCount: 3,
    createdAt: "2025-10-05",
  },
];

const SEED_PROMOS = [
  { code: "FRIENDS20", type: "percentage", value: 20, minPurchase: 125, description: "Friends + Family: Extra 20% off $125+", freeShipping: false, active: true },
  { code: "CK10", type: "percentage", value: 10, minPurchase: 0, description: "10% off your first order", freeShipping: false, active: true },
  { code: "FREESHIP", type: "fixed", value: 0, minPurchase: 75, description: "Free shipping on orders $75+", freeShipping: true, active: true },
  { code: "SAVE25", type: "percentage", value: 25, minPurchase: 200, description: "25% off orders $200+", freeShipping: false, active: true },
];

async function seed() {
  console.log("Starting database seed...\n");

  // Clear and seed products
  console.log("Clearing existing products...");
  const prodSnap = await getDocs(collection(db, "products"));
  for (const d of prodSnap.docs) {
    await deleteDoc(doc(db, "products", d.id));
  }
  console.log(`Cleared ${prodSnap.size} existing products.\n`);

  console.log("Seeding products...");
  for (let i = 0; i < SEED_PRODUCTS.length; i++) {
    await setDoc(doc(collection(db, "products")), SEED_PRODUCTS[i]);
    console.log(`  [${i + 1}/${SEED_PRODUCTS.length}] ${SEED_PRODUCTS[i].name}`);
  }
  console.log(`\nSeeded ${SEED_PRODUCTS.length} products.\n`);

  // Clear and seed promo codes
  console.log("Clearing existing promo codes...");
  const promoSnap = await getDocs(collection(db, "promoCodes"));
  for (const d of promoSnap.docs) {
    await deleteDoc(doc(db, "promoCodes", d.id));
  }
  console.log(`Cleared ${promoSnap.size} existing promo codes.\n`);

  console.log("Seeding promo codes...");
  for (const promo of SEED_PROMOS) {
    await setDoc(doc(collection(db, "promoCodes")), promo);
    console.log(`  ${promo.code} - ${promo.description}`);
  }
  console.log(`\nSeeded ${SEED_PROMOS.length} promo codes.`);

  console.log("\n=== SEED COMPLETE ===");
  console.log(`Products: ${SEED_PRODUCTS.length}`);
  console.log(`Promo Codes: ${SEED_PROMOS.length}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
