"use client";
import { useState } from "react";
import { collection, getDocs, setDoc, doc, deleteDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";

// This is the static product data we'll push to Firestore
const SEED_PRODUCTS = [
  {
    slug: "tech-pique-t-shirt",
    name: "Tech Pique T-Shirt",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Men",
    description: "A lightweight, breathable t-shirt crafted from performance piqué fabric. Features a classic crew neck and the iconic Calvin Klein logo on the chest.",
    details: "Crew neck. Short sleeves. CK logo patch on chest. Ribbed collar. Regular fit. Machine washable.",
    materials: "60% Cotton, 40% Polyester. Machine wash cold. Tumble dry low.",
    price: 59.0,
    salePrice: 35.4,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "Bright White", colorHex: "#FFFFFF", stock: 15 },
      { size: "S", color: "Bright White", colorHex: "#FFFFFF", stock: 22 },
      { size: "M", color: "Bright White", colorHex: "#FFFFFF", stock: 30 },
      { size: "L", color: "Bright White", colorHex: "#FFFFFF", stock: 18 },
      { size: "XL", color: "Bright White", colorHex: "#FFFFFF", stock: 10 },
      { size: "XXL", color: "Bright White", colorHex: "#FFFFFF", stock: 5 },
      { size: "S", color: "Black Beauty", colorHex: "#111111", stock: 20 },
      { size: "M", color: "Black Beauty", colorHex: "#111111", stock: 25 },
      { size: "L", color: "Black Beauty", colorHex: "#111111", stock: 15 },
      { size: "XL", color: "Black Beauty", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 12 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "S", color: "Calvin Navy", colorHex: "#1B2A4A", stock: 14 },
      { size: "M", color: "Calvin Navy", colorHex: "#1B2A4A", stock: 20 },
      { size: "L", color: "Calvin Navy", colorHex: "#1B2A4A", stock: 11 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["basics", "performance", "spring"],
    rating: 4.2,
    reviewCount: 5,
    createdAt: "2026-01-15",
  },
  {
    slug: "slim-tapered-jeans",
    name: "Slim Tapered Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "A modern slim tapered fit in premium stretch denim. Sits below the waist with a slim fit through the hip and thigh that tapers to the ankle.",
    details: "5-pocket styling. Zip fly with button closure. Calvin Klein leather patch at back waist. Slim tapered fit.",
    materials: "98% Cotton, 2% Elastane. Machine wash cold inside out. Tumble dry low.",
    price: 119.0,
    salePrice: 71.4,
    discount: 40,
    images: [],
    variants: [
      { size: "28", color: "Raw Rinse", colorHex: "#1a2744", stock: 10 },
      { size: "30", color: "Raw Rinse", colorHex: "#1a2744", stock: 15 },
      { size: "32", color: "Raw Rinse", colorHex: "#1a2744", stock: 20 },
      { size: "34", color: "Raw Rinse", colorHex: "#1a2744", stock: 12 },
      { size: "36", color: "Raw Rinse", colorHex: "#1a2744", stock: 8 },
      { size: "30", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 14 },
      { size: "32", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 18 },
      { size: "34", color: "Boston Blue Black", colorHex: "#2a3d5c", stock: 10 },
      { size: "30", color: "Light Wash", colorHex: "#a5c4e0", stock: 11 },
      { size: "32", color: "Light Wash", colorHex: "#a5c4e0", stock: 16 },
      { size: "34", color: "Light Wash", colorHex: "#a5c4e0", stock: 9 },
      { size: "30", color: "Black", colorHex: "#111111", stock: 13 },
      { size: "32", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "34", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["denim", "spring", "essentials"],
    rating: 4.5,
    reviewCount: 6,
    createdAt: "2025-11-20",
  },
  {
    slug: "trouser-barrel-jeans",
    name: "Trouser Barrel Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "Wide-leg barrel fit in premium twill. A relaxed, vintage-inspired silhouette with pleated front and cropped length.",
    details: "Pleated front. Zip fly with button closure. Barrel leg silhouette. Cropped length. CK patch at back waist.",
    materials: "100% Cotton. Machine wash cold. Hang dry recommended.",
    price: 149.0,
    salePrice: 89.4,
    discount: 40,
    images: [],
    variants: [
      { size: "30", color: "Khaki", colorHex: "#C3B091", stock: 8 },
      { size: "32", color: "Khaki", colorHex: "#C3B091", stock: 12 },
      { size: "34", color: "Khaki", colorHex: "#C3B091", stock: 10 },
      { size: "30", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "32", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "34", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["denim", "spring", "90s"],
    rating: 4.0,
    reviewCount: 1,
    createdAt: "2026-02-01",
  },
  {
    slug: "varsity-logo-fleece-sweatshirt",
    name: "Varsity Logo Graphic Fleece Sweatshirt",
    category: "Tops",
    subcategory: "Sweatshirts",
    gender: "Men",
    description: "A cozy fleece sweatshirt with oversized varsity-style Calvin Klein logo across the chest.",
    details: "Crew neck. Ribbed cuffs and hem. Large varsity CK logo graphic on chest. Relaxed fit.",
    materials: "80% Cotton, 20% Polyester. Machine wash cold. Tumble dry low.",
    price: 89.0,
    salePrice: 53.4,
    discount: 40,
    images: [],
    variants: [
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 14 },
      { size: "XL", color: "Grey Heather", colorHex: "#9B9B9B", stock: 8 },
      { size: "S", color: "Black Beauty", colorHex: "#111111", stock: 12 },
      { size: "M", color: "Black Beauty", colorHex: "#111111", stock: 20 },
      { size: "L", color: "Black Beauty", colorHex: "#111111", stock: 15 },
      { size: "XL", color: "Black Beauty", colorHex: "#111111", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["casual", "logo", "cozy"],
    rating: 4.3,
    reviewCount: 0,
    createdAt: "2025-12-05",
  },
  {
    slug: "lightweight-windbreaker-jacket",
    name: "Lightweight Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A water-resistant windbreaker with packable design. Features a half-zip front, elastic cuffs, and the CK logo.",
    details: "Half-zip front. Packable into pocket. Elastic cuffs. Drawcord at hem. CK logo embroidery.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 149.0,
    salePrice: 59.6,
    discount: 60,
    images: [],
    variants: [
      { size: "XS", color: "Chase Blue", colorHex: "#4A90D9", stock: 3 },
      { size: "S", color: "Chase Blue", colorHex: "#4A90D9", stock: 7 },
      { size: "M", color: "Chase Blue", colorHex: "#4A90D9", stock: 12 },
      { size: "L", color: "Chase Blue", colorHex: "#4A90D9", stock: 8 },
      { size: "XL", color: "Chase Blue", colorHex: "#4A90D9", stock: 4 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 15 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 11 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 5 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear", "active"],
    rating: 4.6,
    reviewCount: 3,
    createdAt: "2025-10-10",
  },
  {
    slug: "ombre-windbreaker-jacket",
    name: "Ombre Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A standout ombre-dyed windbreaker with gradient colorway. Lightweight water-resistant nylon.",
    details: "Full zip front. Ombre dye effect. Stand collar. Two side pockets. Elastic cuffs and hem.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 199.0,
    salePrice: 79.6,
    discount: 60,
    images: [],
    variants: [
      { size: "S", color: "Orange Gradient", colorHex: "#FF6B35", stock: 6 },
      { size: "M", color: "Orange Gradient", colorHex: "#FF6B35", stock: 10 },
      { size: "L", color: "Orange Gradient", colorHex: "#FF6B35", stock: 8 },
      { size: "XL", color: "Orange Gradient", colorHex: "#FF6B35", stock: 4 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear"],
    rating: 4.1,
    reviewCount: 2,
    createdAt: "2025-09-20",
  },
  {
    slug: "nylon-bomber-jacket",
    name: "Nylon Bomber Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A classic bomber jacket updated in lightweight nylon. Ribbed collar, cuffs and hem.",
    details: "Two-way zip front. Ribbed collar, cuffs, and hem. Two side pockets. Interior pocket.",
    materials: "Shell: 100% Nylon. Lining: 100% Polyester. Machine wash cold.",
    price: 149.0,
    salePrice: 59.6,
    discount: 60,
    images: [],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 9 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 5 },
      { size: "M", color: "Olive", colorHex: "#556B2F", stock: 8 },
      { size: "L", color: "Olive", colorHex: "#556B2F", stock: 11 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["spring", "outerwear", "bomber"],
    rating: 4.4,
    reviewCount: 4,
    createdAt: "2025-10-15",
  },
  {
    slug: "90s-straight-jeans",
    name: "90s Straight Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Men",
    description: "Authentic 90s-inspired straight leg fit. Sits at the waist with a straight fit through hip, thigh, and leg.",
    details: "5-pocket styling. Zip fly with button closure. 90s straight leg. CK leather patch.",
    materials: "99% Cotton, 1% Elastane. Machine wash cold inside out.",
    price: 169.0,
    salePrice: 84.5,
    discount: 50,
    images: [],
    variants: [
      { size: "28", color: "Mid Blue", colorHex: "#4682B4", stock: 8 },
      { size: "30", color: "Mid Blue", colorHex: "#4682B4", stock: 14 },
      { size: "32", color: "Mid Blue", colorHex: "#4682B4", stock: 20 },
      { size: "34", color: "Mid Blue", colorHex: "#4682B4", stock: 12 },
      { size: "36", color: "Mid Blue", colorHex: "#4682B4", stock: 6 },
      { size: "30", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 10 },
      { size: "32", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 15 },
      { size: "34", color: "Vintage Indigo", colorHex: "#2E3A59", stock: 8 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["denim", "90s", "essentials"],
    rating: 4.7,
    reviewCount: 12,
    createdAt: "2025-08-05",
  },
  {
    slug: "modern-cotton-boxer-brief-3-pack",
    name: "Modern Cotton Boxer Brief 3-Pack",
    category: "Underwear",
    subcategory: "Boxer Briefs",
    gender: "Men",
    description: "The iconic Calvin Klein waistband on a cotton stretch boxer brief. Sold in a pack of three.",
    details: "Signature CK waistband. Cotton stretch fabric. Contour pouch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 49.5,
    salePrice: null,
    discount: 0,
    images: [],
    variants: [
      { size: "S", color: "Black/White/Grey", colorHex: "#111111", stock: 25 },
      { size: "M", color: "Black/White/Grey", colorHex: "#111111", stock: 35 },
      { size: "L", color: "Black/White/Grey", colorHex: "#111111", stock: 30 },
      { size: "XL", color: "Black/White/Grey", colorHex: "#111111", stock: 18 },
      { size: "S", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 15 },
      { size: "M", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 22 },
      { size: "L", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 18 },
      { size: "XL", color: "Navy/Blue/Red", colorHex: "#1B2A4A", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["underwear", "basics", "essentials"],
    rating: 4.8,
    reviewCount: 45,
    createdAt: "2025-06-01",
  },
  {
    slug: "cotton-stretch-trunk-3-pack",
    name: "Cotton Stretch Trunk 3-Pack",
    category: "Underwear",
    subcategory: "Trunks",
    gender: "Men",
    description: "Classic Calvin Klein trunks in soft cotton stretch. Signature waistband and low-rise fit.",
    details: "Signature CK waistband. Low-rise fit. Cotton stretch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 49.5,
    salePrice: 34.65,
    discount: 30,
    images: [],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 30 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 25 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 12 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["underwear", "basics"],
    rating: 4.6,
    reviewCount: 22,
    createdAt: "2025-06-15",
  },
  {
    slug: "relaxed-fit-archive-logo-tee",
    name: "Relaxed Fit Archive Logo Tee",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Women",
    description: "An oversized relaxed fit T-shirt featuring the classic Calvin Klein archive logo.",
    details: "Crew neck. Dropped shoulder. CK archive logo print. Relaxed oversized fit.",
    materials: "100% Cotton. Machine wash cold.",
    price: 49.0,
    salePrice: 29.4,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "S", color: "White", colorHex: "#FFFFFF", stock: 20 },
      { size: "M", color: "White", colorHex: "#FFFFFF", stock: 25 },
      { size: "L", color: "White", colorHex: "#FFFFFF", stock: 15 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 22 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["basics", "logo", "casual"],
    rating: 4.4,
    reviewCount: 18,
    createdAt: "2025-09-01",
  },
  {
    slug: "high-rise-straight-jeans",
    name: "High Rise Straight Jeans",
    category: "Bottoms",
    subcategory: "Jeans",
    gender: "Women",
    description: "A flattering high-rise straight leg jean with vintage-inspired washes.",
    details: "High rise. Straight leg. 5-pocket styling. Zip fly with button closure.",
    materials: "99% Cotton, 1% Elastane. Machine wash cold.",
    price: 129.0,
    salePrice: 77.4,
    discount: 40,
    images: [],
    variants: [
      { size: "24", color: "Light Indigo", colorHex: "#8DAFCE", stock: 8 },
      { size: "25", color: "Light Indigo", colorHex: "#8DAFCE", stock: 12 },
      { size: "26", color: "Light Indigo", colorHex: "#8DAFCE", stock: 16 },
      { size: "27", color: "Light Indigo", colorHex: "#8DAFCE", stock: 14 },
      { size: "28", color: "Light Indigo", colorHex: "#8DAFCE", stock: 10 },
      { size: "29", color: "Light Indigo", colorHex: "#8DAFCE", stock: 8 },
      { size: "30", color: "Light Indigo", colorHex: "#8DAFCE", stock: 6 },
      { size: "25", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "26", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "27", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "28", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["denim", "essentials", "90s"],
    rating: 4.3,
    reviewCount: 9,
    createdAt: "2026-01-10",
  },
  {
    slug: "modern-cotton-bralette",
    name: "Modern Cotton Bralette",
    category: "Underwear",
    subcategory: "Bralettes",
    gender: "Women",
    description: "The iconic Calvin Klein bralette in soft modern cotton with signature logo waistband.",
    details: "Signature CK waistband. Unlined. Pullover style. Scoop neck. Racerback.",
    materials: "53% Cotton, 35% Modal, 12% Elastane. Machine wash cold.",
    price: 34.0,
    salePrice: null,
    discount: 0,
    images: [],
    variants: [
      { size: "XS", color: "Black", colorHex: "#111111", stock: 20 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 30 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 28 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 15 },
      { size: "XS", color: "Grey Heather", colorHex: "#9B9B9B", stock: 14 },
      { size: "S", color: "Grey Heather", colorHex: "#9B9B9B", stock: 22 },
      { size: "M", color: "Grey Heather", colorHex: "#9B9B9B", stock: 18 },
      { size: "L", color: "Grey Heather", colorHex: "#9B9B9B", stock: 10 },
      { size: "XS", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 12 },
      { size: "S", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 18 },
      { size: "M", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 16 },
      { size: "L", color: "Nymph's Thigh", colorHex: "#F0D5CE", stock: 8 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["underwear", "iconic", "basics"],
    rating: 4.7,
    reviewCount: 65,
    createdAt: "2025-04-01",
  },
  {
    slug: "cropped-denim-jacket",
    name: "Cropped Denim Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Women",
    description: "A cropped denim jacket with a classic fit and CK branding.",
    details: "Button-front closure. Two chest pockets. Side pockets. Cropped length.",
    materials: "100% Cotton. Machine wash cold.",
    price: 139.0,
    salePrice: 83.4,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "Light Wash", colorHex: "#B8D4E8", stock: 6 },
      { size: "S", color: "Light Wash", colorHex: "#B8D4E8", stock: 10 },
      { size: "M", color: "Light Wash", colorHex: "#B8D4E8", stock: 14 },
      { size: "L", color: "Light Wash", colorHex: "#B8D4E8", stock: 8 },
      { size: "S", color: "Mid Blue", colorHex: "#4682B4", stock: 8 },
      { size: "M", color: "Mid Blue", colorHex: "#4682B4", stock: 12 },
      { size: "L", color: "Mid Blue", colorHex: "#4682B4", stock: 6 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["spring", "denim", "outerwear"],
    rating: 4.5,
    reviewCount: 7,
    createdAt: "2026-02-10",
  },
  {
    slug: "cotton-bikini-3-pack",
    name: "Cotton Bikini 3-Pack",
    category: "Underwear",
    subcategory: "Bikinis",
    gender: "Women",
    description: "Everyday cotton bikini with signature Calvin Klein waistband. 3-pack.",
    details: "Signature CK waistband. Bikini cut. Cotton stretch. 3-pack.",
    materials: "95% Cotton, 5% Elastane. Machine wash cold.",
    price: 39.0,
    salePrice: 27.3,
    discount: 30,
    images: [],
    variants: [
      { size: "XS", color: "Black/White/Grey", colorHex: "#111111", stock: 18 },
      { size: "S", color: "Black/White/Grey", colorHex: "#111111", stock: 25 },
      { size: "M", color: "Black/White/Grey", colorHex: "#111111", stock: 30 },
      { size: "L", color: "Black/White/Grey", colorHex: "#111111", stock: 16 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["underwear", "basics"],
    rating: 4.5,
    reviewCount: 30,
    createdAt: "2025-07-01",
  },
  {
    slug: "slim-fit-stretch-shirt",
    name: "Slim Fit Stretch Dress Shirt",
    category: "Tops",
    subcategory: "Dress Shirts",
    gender: "Men",
    description: "A refined slim-fit dress shirt crafted from stretch cotton poplin.",
    details: "Spread collar. Button-front. Barrel cuffs. Slim fit through body.",
    materials: "97% Cotton, 3% Elastane. Machine wash cold.",
    price: 79.5,
    salePrice: 47.7,
    discount: 40,
    images: [],
    variants: [
      { size: "S", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "M", color: "White", colorHex: "#FFFFFF", stock: 20 },
      { size: "L", color: "White", colorHex: "#FFFFFF", stock: 16 },
      { size: "XL", color: "White", colorHex: "#FFFFFF", stock: 8 },
      { size: "S", color: "Light Blue", colorHex: "#ADD8E6", stock: 10 },
      { size: "M", color: "Light Blue", colorHex: "#ADD8E6", stock: 16 },
      { size: "L", color: "Light Blue", colorHex: "#ADD8E6", stock: 12 },
      { size: "XL", color: "Light Blue", colorHex: "#ADD8E6", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["formal", "essentials", "office"],
    rating: 4.2,
    reviewCount: 11,
    createdAt: "2025-08-15",
  },
  {
    slug: "hooded-softshell-jacket",
    name: "Hooded Softshell Zip Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A versatile hooded softshell jacket. Water-resistant and wind-proof.",
    details: "Full zip front. Attached hood. Softshell stretch fabric. Two zip pockets.",
    materials: "94% Polyester, 6% Elastane. Wipe clean or dry clean.",
    price: 189.0,
    salePrice: 56.7,
    discount: 70,
    images: [],
    variants: [
      { size: "S", color: "Dark Grey", colorHex: "#444444", stock: 5 },
      { size: "M", color: "Dark Grey", colorHex: "#444444", stock: 10 },
      { size: "L", color: "Dark Grey", colorHex: "#444444", stock: 8 },
      { size: "XL", color: "Dark Grey", colorHex: "#444444", stock: 3 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "active", "performance"],
    rating: 4.5,
    reviewCount: 8,
    createdAt: "2025-09-10",
  },
  {
    slug: "ribbed-knit-midi-dress",
    name: "Ribbed Knit Midi Dress",
    category: "Tops",
    subcategory: "Dresses",
    gender: "Women",
    description: "A bodycon ribbed knit midi dress with minimalist design.",
    details: "Scoop neck. Sleeveless. Bodycon fit. Midi length. CK logo detail.",
    materials: "68% Viscose, 27% Polyester, 5% Elastane. Hand wash cold.",
    price: 99.0,
    salePrice: 59.4,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "XS", color: "Camel", colorHex: "#C19A6B", stock: 6 },
      { size: "S", color: "Camel", colorHex: "#C19A6B", stock: 10 },
      { size: "M", color: "Camel", colorHex: "#C19A6B", stock: 12 },
      { size: "L", color: "Camel", colorHex: "#C19A6B", stock: 5 },
    ],
    isBestSeller: false,
    isNew: true,
    tags: ["dresses", "minimalist", "spring"],
    rating: 4.6,
    reviewCount: 4,
    createdAt: "2026-02-20",
  },
  {
    slug: "kids-logo-t-shirt",
    name: "Kids Logo T-Shirt",
    category: "Tops",
    subcategory: "T-Shirts",
    gender: "Kids",
    description: "A mini version of the iconic Calvin Klein logo tee.",
    details: "Crew neck. Short sleeves. CK logo print on chest. Regular fit.",
    materials: "100% Cotton. Machine wash cold.",
    price: 29.0,
    salePrice: null,
    discount: 0,
    images: [],
    variants: [
      { size: "4", color: "White", colorHex: "#FFFFFF", stock: 12 },
      { size: "5", color: "White", colorHex: "#FFFFFF", stock: 15 },
      { size: "6", color: "White", colorHex: "#FFFFFF", stock: 18 },
      { size: "7", color: "White", colorHex: "#FFFFFF", stock: 14 },
      { size: "8", color: "White", colorHex: "#FFFFFF", stock: 10 },
      { size: "4", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "5", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "6", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "7", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: true,
    isNew: false,
    tags: ["kids", "basics", "logo"],
    rating: 4.8,
    reviewCount: 20,
    createdAt: "2025-07-15",
  },
  {
    slug: "reversible-puffer-jacket",
    name: "Allover Emblem Logo Reversible Puffer Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A reversible puffer jacket with CK monogram and solid color.",
    details: "Reversible design. Stand collar. Zip front. CK monogram print.",
    materials: "Shell: 100% Polyester. Fill: 80% Down, 20% Feather. Dry clean only.",
    price: 329.0,
    salePrice: 98.7,
    discount: 70,
    images: [],
    variants: [
      { size: "S", color: "Black/Monogram", colorHex: "#111111", stock: 4 },
      { size: "M", color: "Black/Monogram", colorHex: "#111111", stock: 7 },
      { size: "L", color: "Black/Monogram", colorHex: "#111111", stock: 5 },
      { size: "XL", color: "Black/Monogram", colorHex: "#111111", stock: 2 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "puffer", "sale"],
    rating: 4.3,
    reviewCount: 6,
    createdAt: "2025-08-01",
  },
  {
    slug: "relaxed-hoodie-sweatshirt",
    name: "Relaxed Hoodie Sweatshirt",
    category: "Tops",
    subcategory: "Sweatshirts",
    gender: "Women",
    description: "An oversized relaxed hoodie with kangaroo pocket and drawstring hood.",
    details: "Drawstring hood. Kangaroo pocket. Ribbed cuffs and hem. CK logo embroidery.",
    materials: "80% Cotton, 20% Polyester. Machine wash cold.",
    price: 89.0,
    salePrice: 53.4,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 10 },
      { size: "S", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 16 },
      { size: "M", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 20 },
      { size: "L", color: "Light Grey Heather", colorHex: "#D3D3D3", stock: 12 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 18 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 10 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["casual", "cozy", "basics"],
    rating: 4.4,
    reviewCount: 14,
    createdAt: "2025-10-20",
  },
  {
    slug: "tech-knit-track-jacket",
    name: "Tech Knit Track Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A sporty track jacket in lightweight tech knit with zip front.",
    details: "Full zip front. Stand collar. Contrast trim at collar and cuffs. Side pockets.",
    materials: "90% Polyester, 10% Elastane. Machine wash cold.",
    price: 189.0,
    salePrice: 56.7,
    discount: 70,
    images: [],
    variants: [
      { size: "S", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 10 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 8 },
      { size: "XL", color: "Black", colorHex: "#111111", stock: 4 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["active", "outerwear", "performance"],
    rating: 4.2,
    reviewCount: 5,
    createdAt: "2025-09-25",
  },
  {
    slug: "cotton-modal-sleep-set",
    name: "Cotton Modal Sleep Set",
    category: "Underwear",
    subcategory: "Sleepwear",
    gender: "Women",
    description: "A luxurious sleep set in soft cotton modal.",
    details: "Short sleeve crew neck top. Elastic waist shorts. CK logo.",
    materials: "50% Cotton, 50% Modal. Machine wash cold.",
    price: 68.0,
    salePrice: 40.8,
    discount: 40,
    images: [],
    variants: [
      { size: "XS", color: "Shoreline", colorHex: "#6EA4BF", stock: 8 },
      { size: "S", color: "Shoreline", colorHex: "#6EA4BF", stock: 14 },
      { size: "M", color: "Shoreline", colorHex: "#6EA4BF", stock: 18 },
      { size: "L", color: "Shoreline", colorHex: "#6EA4BF", stock: 10 },
      { size: "XS", color: "Black", colorHex: "#111111", stock: 6 },
      { size: "S", color: "Black", colorHex: "#111111", stock: 12 },
      { size: "M", color: "Black", colorHex: "#111111", stock: 14 },
      { size: "L", color: "Black", colorHex: "#111111", stock: 8 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["sleepwear", "essentials"],
    rating: 4.6,
    reviewCount: 16,
    createdAt: "2025-11-01",
  },
  {
    slug: "monogram-windbreaker-jacket",
    name: "Allover Monogram Windbreaker Jacket",
    category: "Outerwear",
    subcategory: "Jackets",
    gender: "Men",
    description: "A lightweight windbreaker with allover CK monogram print.",
    details: "Full zip front. Hood with drawcord. Allover CK monogram. Two side pockets.",
    materials: "100% Nylon. Machine wash cold. Hang dry.",
    price: 179.0,
    salePrice: 71.6,
    discount: 60,
    images: [],
    variants: [
      { size: "S", color: "Autumn Green", colorHex: "#556B2F", stock: 5 },
      { size: "M", color: "Autumn Green", colorHex: "#556B2F", stock: 9 },
      { size: "L", color: "Autumn Green", colorHex: "#556B2F", stock: 7 },
      { size: "S", color: "Merlot", colorHex: "#722F37", stock: 4 },
      { size: "M", color: "Merlot", colorHex: "#722F37", stock: 8 },
      { size: "L", color: "Merlot", colorHex: "#722F37", stock: 6 },
    ],
    isBestSeller: false,
    isNew: false,
    tags: ["outerwear", "monogram", "spring"],
    rating: 4.0,
    reviewCount: 3,
    createdAt: "2025-10-05",
  },
];

const SEED_PROMOS = [
  { code: "FRIENDS20", type: "percentage", value: 20, minPurchase: 125, description: "Friends + Family: Extra 20% off $125+", freeShipping: false, active: true },
  { code: "CK10", type: "percentage", value: 10, minPurchase: 0, description: "10% off your first order", freeShipping: false, active: true },
  { code: "FREESHIP", type: "fixed", value: 0, minPurchase: 75, description: "Free shipping on orders $75+", freeShipping: true, active: true },
  { code: "SAVE25", type: "percentage", value: 25, minPurchase: 200, description: "25% off orders $200+", freeShipping: false, active: true },
];

export default function SeedPage() {
  const [status, setStatus] = useState("");
  const [seeding, setSeeding] = useState(false);

  const seedProducts = async () => {
    setSeeding(true);
    setStatus("Seeding products...");
    try {
      // Clear existing
      const snap = await getDocs(collection(db, "products"));
      for (const d of snap.docs) {
        await deleteDoc(doc(db, "products", d.id));
      }
      setStatus(`Cleared ${snap.size} existing products. Adding new ones...`);

      for (let i = 0; i < SEED_PRODUCTS.length; i++) {
        await setDoc(doc(collection(db, "products")), SEED_PRODUCTS[i]);
        setStatus(`Added product ${i + 1}/${SEED_PRODUCTS.length}: ${SEED_PRODUCTS[i].name}`);
      }

      // Seed promo codes
      const promoSnap = await getDocs(collection(db, "promoCodes"));
      for (const d of promoSnap.docs) {
        await deleteDoc(doc(db, "promoCodes", d.id));
      }
      for (const promo of SEED_PROMOS) {
        await setDoc(doc(collection(db, "promoCodes")), promo);
      }

      setStatus(`Done! Seeded ${SEED_PRODUCTS.length} products and ${SEED_PROMOS.length} promo codes.`);
    } catch (err) {
      setStatus(`Error: ${err.message}`);
    }
    setSeeding(false);
  };

  return (
    <div className="max-w-xl mx-auto py-20 px-4 text-center">
      <h1 className="text-2xl font-bold mb-4">Database Seed Tool</h1>
      <p className="text-sm text-gray-500 mb-8">
        This will clear all existing products and promo codes in Firestore and replace them with the seed data ({SEED_PRODUCTS.length} products, {SEED_PROMOS.length} promo codes).
      </p>
      <button
        onClick={seedProducts}
        disabled={seeding}
        className="bg-black text-white px-8 py-3 text-sm font-medium hover:bg-gray-900 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {seeding ? "Seeding..." : "Seed Database"}
      </button>
      {status && (
        <div className="mt-6 p-4 bg-gray-50 border border-gray-200 text-sm text-left whitespace-pre-wrap">
          {status}
        </div>
      )}
    </div>
  );
}
